apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-dans
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-dans
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-dans
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-dans
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-dans
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tjzb-tenant/rhtap-demo-app/hacbs-test-project-dans@sha256:c775c6895814cef2cbaab1f702009a01574fe62064d912998468e6de7377fb21
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
